# MERGE WITH FRONTEND COMPOSE FILE 
version: "3.8"
services:
  web:
    image: ghcr.io/miouss/lolmood-frontend:latest
    container_name: lolmood_web
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    environment:
      NODE_ENV : production
  certbot:
    image: certbot/certbot:latest
    volumes: 
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
